import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
import { Colors } from '../../assets/colors';

const { width: windowWidth, height: windowHeight } = Dimensions.get('window');

const FeedbackScreenStyle = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: responsiveWidth(4),
    paddingVertical: responsiveHeight(1.5),
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    width: responsiveWidth(10),
    height: responsiveWidth(10),
    borderRadius: responsiveWidth(5),
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: responsiveFontSize(2.2),
    fontWeight: '700',
    color: '#1A1A1A',
    fontFamily: 'Poppins-SemiBold',
  },
  headerPlaceholder: {
    width: responsiveWidth(10),
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: responsiveHeight(2),
  },
  formContainer: {
    paddingHorizontal: responsiveWidth(5),
    paddingTop: responsiveHeight(3),
  },
  illustrationContainer: {
    alignItems: 'center',
    marginBottom: responsiveHeight(2.5),
  },
  illustrationCircle: {
    width: responsiveWidth(20),
    height: responsiveWidth(20),
    borderRadius: responsiveWidth(10),
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formTitle: {
    fontSize: responsiveFontSize(2.4),
    fontWeight: '700',
    color: '#1A1A1A',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginBottom: responsiveHeight(1),
  },
  formSubtitle: {
    fontSize: responsiveFontSize(1.6),
    color: '#8E8E93',
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginBottom: responsiveHeight(4),
    paddingHorizontal: responsiveWidth(5),
  },
  inputGroup: {
    marginBottom: responsiveHeight(2.5),
  },
  inputLabel: {
    fontSize: responsiveFontSize(1.7),
    fontWeight: '600',
    color: '#1A1A1A',
    fontFamily: 'Poppins-Medium',
    marginBottom: responsiveHeight(1),
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: responsiveWidth(3),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: responsiveWidth(4),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  textAreaContainer: {
    alignItems: 'flex-start',
  },
  inputIcon: {
    marginRight: responsiveWidth(3),
  },
  textInput: {
    flex: 1,
    fontSize: responsiveFontSize(1.7),
    color: '#1A1A1A',
    fontFamily: 'Poppins-Regular',
    paddingVertical: responsiveHeight(1.8),
  },
  textArea: {
    height: responsiveHeight(18),
    textAlignVertical: 'top',
    paddingTop: responsiveHeight(1.5),
  },
  characterCount: {
    alignItems: 'flex-end',
    marginTop: responsiveHeight(-1.5),
  },
  characterCountText: {
    fontSize: responsiveFontSize(1.3),
    color: '#BDBDBD',
    fontFamily: 'Poppins-Regular',
  },
  buttonContainer: {
    paddingHorizontal: responsiveWidth(5),
    paddingVertical: responsiveHeight(2),
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3b82f6',
    borderRadius: responsiveWidth(3),
    paddingVertical: responsiveHeight(2),
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    gap: responsiveWidth(2),
  },
  submitButtonDisabled: {
    backgroundColor: '#BDBDBD',
    shadowColor: '#BDBDBD',
  },
  submitButtonText: {
    fontSize: responsiveFontSize(1.8),
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Poppins-SemiBold',
  },
  successContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: responsiveWidth(8),
    paddingTop: responsiveHeight(5),
  },
  lottieContainer: {
    width: responsiveWidth(60),
    height: responsiveHeight(25),
    alignItems: 'center',
    justifyContent: 'center',
  },
  animationCtn: {
    width: '100%',
    height: '100%',
  },
  successTitle: {
    fontSize: responsiveFontSize(3),
    fontWeight: '700',
    color: '#1A1A1A',
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    marginTop: responsiveHeight(2),
    marginBottom: responsiveHeight(1),
  },
  successSubtitle: {
    fontSize: responsiveFontSize(1.8),
    color: '#4CAF50',
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
    marginBottom: responsiveHeight(2),
  },
  successMessage: {
    fontSize: responsiveFontSize(1.5),
    color: '#8E8E93',
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    lineHeight: responsiveHeight(3),
    paddingHorizontal: responsiveWidth(5),
  },
  container: {
    flex: 1,
  },
  contentCtn: {
    flex: 1,
    marginLeft: responsiveWidth(8),
  },
  view2: {
    padding: responsiveWidth(1),
    paddingHorizontal: responsiveWidth(5),
    marginBottom: responsiveHeight(8),
  },
  profileButton: {
    overflow: 'hidden',
    alignItems: 'center',
    position: 'relative',
    borderRadius: responsiveHeight(6),
    marginTop: responsiveHeight(20),
  },
  image: {
    flex: 1,
    transform: [{ scale: 1.5 }],
  },
  logoImgContainer: {
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginImg: {
    height: responsiveHeight(15),
    width: responsiveHeight(20.52),
  },
  congratesText: {
    fontSize: responsiveFontSize(4),
    fontFamily: 'Rubik-Medium',
    textAlign: 'center',
  },
  sendTxt: {
    color: Colors.activeprimary,
    fontSize: responsiveFontSize(2),
    fontFamily: 'Rubik-Regular',
    borderBottomWidth: 1,
    borderColor: Colors.activeprimary,
    marginBottom: responsiveHeight(2),
    width: responsiveWidth(38),
  },
  buttonmainCtn: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  headingText: {
    fontSize: responsiveFontSize(1.8),
    fontFamily: 'Rubik-Light',
    width: responsiveWidth(82),
    marginTop: responsiveHeight(3.7),
  },
  dropdown: {
    height: responsiveHeight(4),
    width: responsiveWidth(80),
    borderBottomColor: 'black',
    borderBottomWidth: 0.5,
    borderRadius: responsiveWidth(1),
    paddingHorizontal: 8,
    marginTop: responsiveHeight(1),
    backgroundColor: Colors.white,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    position: 'absolute',
    backgroundColor: Colors.white,
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
    color: Colors.black,
  },
  placeholderStyle: {
    fontFamily: 'Rubik-Regular',
    fontSize: responsiveFontSize(1.8),
    lineHeight: responsiveFontSize(2),
    color: '#333333',
    backgroundColor: 'white',
  },
  selectedTextStyle: {
    fontFamily: 'Rubik-Regular',
    fontSize: responsiveFontSize(1.8),
    lineHeight: responsiveFontSize(2),
    color: '#333333',
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
    color: Colors.black,
  },
  buttonCtn: {
    marginTop: responsiveHeight(2),
  },
});

export default FeedbackScreenStyle;
